/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package me.garodriguezlp;

import static org.junit.jupiter.api.Assertions.assertAll;
import static org.junit.jupiter.api.Assertions.assertFalse;

import org.junit.jupiter.api.Test;


class AppTest {

    private App sut = new App();

    @Test
    void isPrime() {
        assertAll(
            () -> assertFalse(sut.isPrime(1))
        );
    }
}
